// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxzocaDslV4tDbSu3fVKGiw-18sjCRbRk',
    appId: '1:694648590920:web:8abc313e0b83dae6d0fe7d',
    messagingSenderId: '694648590920',
    projectId: 'flex-49dfe',
    authDomain: 'flex-49dfe.firebaseapp.com',
    databaseURL: 'https://flex-49dfe-default-rtdb.firebaseio.com',
    storageBucket: 'flex-49dfe.appspot.com',
    measurementId: 'G-P22FQC4GF8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCh2K8SceEfgnJ4hNHW8QTm4CJIPa0LmDA',
    appId: '1:694648590920:android:4499f914b76df4c7d0fe7d',
    messagingSenderId: '694648590920',
    projectId: 'flex-49dfe',
    databaseURL: 'https://flex-49dfe-default-rtdb.firebaseio.com',
    storageBucket: 'flex-49dfe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKT-ZC7xP4oXVTTdwhhrRxEcPmv4EBx98',
    appId: '1:694648590920:ios:ab8cd980ae893475d0fe7d',
    messagingSenderId: '694648590920',
    projectId: 'flex-49dfe',
    databaseURL: 'https://flex-49dfe-default-rtdb.firebaseio.com',
    storageBucket: 'flex-49dfe.appspot.com',
    iosBundleId: 'com.codeforany.fitness',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBxzocaDslV4tDbSu3fVKGiw-18sjCRbRk',
    appId: '1:694648590920:web:1489c13dbf4b7610d0fe7d',
    messagingSenderId: '694648590920',
    projectId: 'flex-49dfe',
    authDomain: 'flex-49dfe.firebaseapp.com',
    databaseURL: 'https://flex-49dfe-default-rtdb.firebaseio.com',
    storageBucket: 'flex-49dfe.appspot.com',
    measurementId: 'G-BZ7T12SGPV',
  );

}